-- AlterTable
ALTER TABLE "Receipt" ADD COLUMN IF NOT EXISTS "templateVersion" TEXT NOT NULL DEFAULT 'v1';
ALTER TABLE "Receipt" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "Receipt" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'GENERATED';
ALTER TABLE "Receipt" ADD COLUMN IF NOT EXISTS "generatedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Receipt" ADD COLUMN IF NOT EXISTS "sentAt" TIMESTAMP(3);
